version: '3'
services:
  spotify:
    container_name: spotify
    image: spotify:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - 7555:7555
    networks:
      - default
      - npm_network

networks:
  npm_network:
    external: true
    name: proxy-network

