import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Layout from "@/components/Layout";
import SessionProvider from "@/components/SessionProvider";

import "@/app/styles/globals.css";
import "@/app/styles/vinyl.scss";
import "@/app/styles/visualizer.scss";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children?: React.ReactNode;
};

async function RootLayout({ children }: Props) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Layout>{children}</Layout>
        </SessionProvider>
      </body>
    </html>
  );
}

export default RootLayout;
