export const mockTrack: SpotifyApi.TrackObjectFull = {
  album: {
    album_type: "album",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3bRGJQd7b4lE3ZAEMfOXJp",
        },
        href: "https://api.spotify.com/v1/artists/3bRGJQd7b4lE3ZAEMfOXJp",
        id: "3bRGJQd7b4lE3ZAEMfOXJp",
        name: "Luidji",
        type: "artist",
        uri: "spotify:artist:3bRGJQd7b4lE3ZAEMfOXJp",
      },
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK",
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/0MdN6wfUWZtMFXV0ESjYuf",
    },
    href: "https://api.spotify.com/v1/albums/0MdN6wfUWZtMFXV0ESjYuf",
    id: "0MdN6wfUWZtMFXV0ESjYuf",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b2731c0c1c345a93d144465e7cf8",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e021c0c1c345a93d144465e7cf8",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d000048511c0c1c345a93d144465e7cf8",
        width: 64,
      },
    ],
    name: "Saison 00",
    release_date: "2023-06-22",
    release_date_precision: "day",
    total_tracks: 14,
    type: "album",
    uri: "spotify:album:0MdN6wfUWZtMFXV0ESjYuf",
  },
  artists: [
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/3bRGJQd7b4lE3ZAEMfOXJp",
      },
      href: "https://api.spotify.com/v1/artists/3bRGJQd7b4lE3ZAEMfOXJp",
      id: "3bRGJQd7b4lE3ZAEMfOXJp",
      name: "Luidji",
      type: "artist",
      uri: "spotify:artist:3bRGJQd7b4lE3ZAEMfOXJp",
    },
  ],
  available_markets: [
    "AR",
    "AU",
    "AT",
    "BE",
    "BO",
    "BR",
    "BG",
    "CA",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DK",
    "DO",
    "DE",
    "EC",
    "EE",
    "SV",
    "FI",
    "FR",
    "GR",
    "GT",
    "HN",
    "HK",
    "HU",
    "IS",
    "IE",
    "IT",
    "LV",
    "LT",
    "LU",
    "MY",
    "MT",
    "MX",
    "NL",
    "NZ",
    "NI",
    "NO",
    "PA",
    "PY",
    "PE",
    "PH",
    "PL",
    "PT",
    "SG",
    "SK",
    "ES",
    "SE",
    "CH",
    "TW",
    "TR",
    "UY",
    "US",
    "GB",
    "AD",
    "LI",
    "MC",
    "ID",
    "JP",
    "TH",
    "VN",
    "RO",
    "IL",
    "ZA",
    "SA",
    "AE",
    "BH",
    "QA",
    "OM",
    "KW",
    "EG",
    "MA",
    "DZ",
    "TN",
    "LB",
    "JO",
    "PS",
    "IN",
    "KZ",
    "MD",
    "UA",
    "AL",
    "BA",
    "HR",
    "ME",
    "MK",
    "RS",
    "SI",
    "KR",
    "BD",
    "PK",
    "LK",
    "GH",
    "KE",
    "NG",
    "TZ",
    "UG",
    "AG",
    "AM",
    "BS",
    "BB",
    "BZ",
    "BT",
    "BW",
    "BF",
    "CV",
    "CW",
    "DM",
    "FJ",
    "GM",
    "GE",
    "GD",
    "GW",
    "GY",
    "HT",
    "JM",
    "KI",
    "LS",
    "LR",
    "MW",
    "MV",
    "ML",
    "MH",
    "FM",
    "NA",
    "NR",
    "NE",
    "PW",
    "PG",
    "WS",
    "SM",
    "ST",
    "SN",
    "SC",
    "SL",
    "SB",
    "KN",
    "LC",
    "VC",
    "SR",
    "TL",
    "TO",
    "TT",
    "TV",
    "VU",
    "AZ",
    "BN",
    "BI",
    "KH",
    "CM",
    "TD",
    "KM",
    "GQ",
    "SZ",
    "GA",
    "GN",
    "KG",
    "LA",
    "MO",
    "MR",
    "MN",
    "NP",
    "RW",
    "TG",
    "UZ",
    "ZW",
    "BJ",
    "MG",
    "MU",
    "MZ",
    "AO",
    "CI",
    "DJ",
    "ZM",
    "CD",
    "CG",
    "IQ",
    "LY",
    "TJ",
    "VE",
    "ET",
    "XK",
  ],
  disc_number: 1,
  duration_ms: 207000,
  explicit: false,
  external_ids: {
    isrc: "FR9W12320125",
  },
  external_urls: {
    spotify: "https://open.spotify.com/track/6KRAtvUZrYdCgVCYgl8YJt",
  },
  href: "https://api.spotify.com/v1/tracks/6KRAtvUZrYdCgVCYgl8YJt",
  id: "6KRAtvUZrYdCgVCYgl8YJt",
  is_local: false,
  name: "Télefoot",
  popularity: 59,
  preview_url:
    "https://p.scdn.co/mp3-preview/485b589c3b2ad62f22a3c637587784826d9632d9?cid=2a8bd4a7cfc440b2836d1cf4b0bf6b8f",
  track_number: 2,
  type: "track",
  uri: "spotify:track:6KRAtvUZrYdCgVCYgl8YJt",
};
